create table databasechangeloglock
(
    id integer not null
        constraint databasechangeloglock_pkey
            primary key,
    locked boolean not null,
    lockgranted timestamp,
    lockedby varchar(255)
);

alter table databasechangeloglock owner to helmes_user;

create table databasechangelog
(
    id varchar(255) not null,
    author varchar(255) not null,
    filename varchar(255) not null,
    dateexecuted timestamp not null,
    orderexecuted integer not null,
    exectype varchar(10) not null,
    md5sum varchar(35),
    description varchar(255),
    comments varchar(255),
    tag varchar(255),
    liquibase varchar(20),
    contexts varchar(255),
    labels varchar(255),
    deployment_id varchar(10)
);

alter table databasechangelog owner to helmes_user;

create table category
(
    id bigint generated by default as identity
        constraint pk_category
            primary key,
    name varchar(255) not null,
    parent_id bigint
        constraint fk_category_on_parent
            references category
);

alter table category owner to helmes_user;

create table application
(
    id bigint generated by default as identity
        constraint pk_application
            primary key,
    name varchar(255) not null,
    token varchar(255) not null,
    terms boolean not null
);

alter table application owner to helmes_user;

create table application_categories
(
    application_id bigint not null,
    categories_id bigint not null
);

alter table application_categories owner to helmes_user;

